on:
  workflow_dispatch:
  pull_request:
  pull_request_target:
  push:
    branches: [main]

jobs:
  flake-checker:
    name: "Flake Checker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
